import type { Metadata } from "next";
import { MenuLateral } from "../shared/components";
import { AppThemeProvider, DrawerProvider } from "../shared/contexts";
import "../styles/globals.scss";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppThemeProvider>
      <DrawerProvider>
        <MenuLateral>{children}</MenuLateral>
      </DrawerProvider>
    </AppThemeProvider>
  );
}
